### ISSUE TITLE
Check file access permissions

### ISSUE THREAD

**Issue by ed-cooper** [ed-cooper/lecture-hoarder#17]
Currently we assume we can read from folders, create new files, etc.

If this is not the case, an exception occurs with a traceback displayed to the user:

```
Traceback (most recent call last):
  File "run.py", line 199, in <module>
    os.makedirs(course_dir, exist_ok=True)
  File "/usr/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/media/edward/Mass Storage'
```

Although the problem is clearly identified in the error, we should aim to make the message more user friendly through proper checks

**Comment by ed-cooper** [comment]
Related to #25
